version: '3'

services:
  wordpress:
    image: vampiro_wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config.php:/var/www/html/wp-config.php
    command: ["apache2-foreground"]
    networks:
      - shared_network
    environment:
      - WORDPRESS_DB_HOST=$MYSQL_HOST:$MYSQL_PORT
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - APACHE_SERVER_NAME=$APACHE_SERVER_NAME
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=$LETSENCRYPT_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

networks:
  shared_network:
    external: true